package com.broker.domain;

public class WxUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_openid
     *
     * @mbg.generated
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_nickName
     *
     * @mbg.generated
     */
    private String wxNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_country
     *
     * @mbg.generated
     */
    private String wxCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_province
     *
     * @mbg.generated
     */
    private String wxProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_city
     *
     * @mbg.generated
     */
    private String wxCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_avatarUrl
     *
     * @mbg.generated
     */
    private String wxAvatarurl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.uid
     *
     * @return the value of wx_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.uid
     *
     * @param uid the value for wx_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_openid
     *
     * @return the value of wx_user.wx_openid
     *
     * @mbg.generated
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_openid
     *
     * @param wxOpenid the value for wx_user.wx_openid
     *
     * @mbg.generated
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid == null ? null : wxOpenid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_nickName
     *
     * @return the value of wx_user.wx_nickName
     *
     * @mbg.generated
     */
    public String getWxNickname() {
        return wxNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_nickName
     *
     * @param wxNickname the value for wx_user.wx_nickName
     *
     * @mbg.generated
     */
    public void setWxNickname(String wxNickname) {
        this.wxNickname = wxNickname == null ? null : wxNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_country
     *
     * @return the value of wx_user.wx_country
     *
     * @mbg.generated
     */
    public String getWxCountry() {
        return wxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_country
     *
     * @param wxCountry the value for wx_user.wx_country
     *
     * @mbg.generated
     */
    public void setWxCountry(String wxCountry) {
        this.wxCountry = wxCountry == null ? null : wxCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_province
     *
     * @return the value of wx_user.wx_province
     *
     * @mbg.generated
     */
    public String getWxProvince() {
        return wxProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_province
     *
     * @param wxProvince the value for wx_user.wx_province
     *
     * @mbg.generated
     */
    public void setWxProvince(String wxProvince) {
        this.wxProvince = wxProvince == null ? null : wxProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_city
     *
     * @return the value of wx_user.wx_city
     *
     * @mbg.generated
     */
    public String getWxCity() {
        return wxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_city
     *
     * @param wxCity the value for wx_user.wx_city
     *
     * @mbg.generated
     */
    public void setWxCity(String wxCity) {
        this.wxCity = wxCity == null ? null : wxCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_avatarUrl
     *
     * @return the value of wx_user.wx_avatarUrl
     *
     * @mbg.generated
     */
    public String getWxAvatarurl() {
        return wxAvatarurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_avatarUrl
     *
     * @param wxAvatarurl the value for wx_user.wx_avatarUrl
     *
     * @mbg.generated
     */
    public void setWxAvatarurl(String wxAvatarurl) {
        this.wxAvatarurl = wxAvatarurl == null ? null : wxAvatarurl.trim();
    }
}