package com.broker.domain;

public class WxUser {
    /**
     *
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_openid
     *
     * @mbg.generated
     */
    private String wxOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_nickName
     *
     * @mbg.generated
     */
    private String wxNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_country
     *
     * @mbg.generated
     */
    private String wxCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_province
     *
     * @mbg.generated
     */
    private String wxProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_city
     *
     * @mbg.generated
     */
    private String wxCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_user.wx_avatarUrl
     *
     * @mbg.generated
     */
    private String wxAvatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.uid
     *
     * @return the value of wx_user.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.uid
     *
     * @param uid the value for wx_user.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_openid
     *
     * @return the value of wx_user.wx_openid
     *
     * @mbg.generated
     */
    public String getWxOpenId() {
        return wxOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_openid
     *
     * @param wxOpenId the value for wx_user.wx_openid
     *
     * @mbg.generated
     */
    public void setWxOpenId(String wxOpenId) {
        this.wxOpenId = wxOpenId == null ? null : wxOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_nickName
     *
     * @return the value of wx_user.wx_nickName
     *
     * @mbg.generated
     */
    public String getWxNickname() {
        return wxNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_nickName
     *
     * @param wxNickName the value for wx_user.wx_nickName
     *
     * @mbg.generated
     */
    public void setWxNickName(String wxNickName) {
        this.wxNickName = wxNickName == null ? null : wxNickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_country
     *
     * @return the value of wx_user.wx_country
     *
     * @mbg.generated
     */
    public String getWxCountry() {
        return wxCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_country
     *
     * @param wxCountry the value for wx_user.wx_country
     *
     * @mbg.generated
     */
    public void setWxCountry(String wxCountry) {
        this.wxCountry = wxCountry == null ? null : wxCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_province
     *
     * @return the value of wx_user.wx_province
     *
     * @mbg.generated
     */
    public String getWxProvince() {
        return wxProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_province
     *
     * @param wxProvince the value for wx_user.wx_province
     *
     * @mbg.generated
     */
    public void setWxProvince(String wxProvince) {
        this.wxProvince = wxProvince == null ? null : wxProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_city
     *
     * @return the value of wx_user.wx_city
     *
     * @mbg.generated
     */
    public String getWxCity() {
        return wxCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_city
     *
     * @param wxCity the value for wx_user.wx_city
     *
     * @mbg.generated
     */
    public void setWxCity(String wxCity) {
        this.wxCity = wxCity == null ? null : wxCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_user.wx_avatarUrl
     *
     * @return the value of wx_user.wx_avatarUrl
     *
     * @mbg.generated
     */
    public String getWxAvatarUrl() {
        return wxAvatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_user.wx_avatarUrl
     *
     * @param wxAvatarUrl the value for wx_user.wx_avatarUrl
     *
     * @mbg.generated
     */
    public void setWxAvatarurl(String wxAvatarUrl) {
        this.wxAvatarUrl = wxAvatarUrl == null ? null : wxAvatarUrl.trim();
    }

    private String code;

    private String encryptedData;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getEncryptedData() {
        return encryptedData;
    }

    public void setEncryptedData(String encryptedData) {
        this.encryptedData = encryptedData;
    }
}